version: '3.8'
services:
  kir-pay-db:
    image: postgres:17-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - database_folder:/var/lib/postgresql/data
    networks:
      - kir-pay-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  kir-pay-backend:
    image: ghcr.io/simonyiszk/kir-pay:latest
    env_file:
      - .env
    environment:
      SERVER_PORT: 8080
      DATABASE_HOST: kir-pay-db
    restart: always
    ports:
      - "8001:8080"
    networks:
      - kir-pay-network
    depends_on:
      kir-pay-db:
        condition: service_healthy
  kir-pay-frontend:
    build:
      context: ./frontend
    image: ghcr.io/simonyiszk/kir-pay-frontend:latest
    env_file:
      - .env
    restart: always
    ports:
      - "3000:80"
networks:
  kir-pay-network:
volumes:
  database_folder:
    driver: local
