version: '3.8'
services:
  db-x:
    image: postgres:16.4
    restart: always
    env_file:
      - .env
    volumes:
      - database_folder:/var/lib/postgresql/data
    networks:
      - network-x
  backend-x:
    image: kir-dev/paybasz:latest
    env_file:
      - .env
    environment:
      SERVER_PORT: 8080
      DATABASE_HOST: db-x
    restart: always
    ports:
      - "8001:8080"
    networks:
      - network-x
    depends_on:
      - db-x
networks:
  network-x:
volumes:
  database_folder:
    driver: local
