version: '3.8'
services:
  db-x:
    image: postgres:15.4
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: paybasz
    volumes:
      - database_folder:/var/lib/postgresql/data
    networks:
      - network-x
  backend-x:
    build: ./backend
    env_file:
      - .env
    environment:
      SERVER_PORT: 8080
      DATABASE_HOST: db-x
    restart: always
    ports:
      - "8001:8080"
    networks:
      - network-x
    depends_on:
      - db-x
  mobile-x:
    build: ./mobile
    env_file:
      - .env
    environment:
      SERVER_PORT: 8080
    restart: always
    ports:
      - "8002:8080"
networks:
  network-x:
volumes:
  database_folder:
    driver: local
