apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.global.postgresql.auth.username | quote }}{{ else }}{{ .Values.externalDatabase.username | quote }}{{ end }}
  POSTGRES_PASSWORD: {{ if .Values.postgresql.enabled }}{{ required "postgresql.global.postgresql.auth.password is required" .Values.postgresql.global.postgresql.auth.password | quote }}{{ else }}{{ required "externalDatabase.password is required" .Values.externalDatabase.password | quote }}{{ end }}
  ADMINISTRATOR_USERNAME: {{ .Values.app.administrator.username | quote }}
  ADMINISTRATOR_PASSWORD: {{ required "app.administrator.password is required" .Values.app.administrator.password | quote }}
