apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  strategy:
    type: {{ .Values.app.strategyType }}
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.app.image }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: DATABASE_HOST
              value: {{ .Release.Name }}-postgresql:5432
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.global.postgresql.auth.database }}
            - name: CURRENCY_SYMBOL
              value: {{ .Values.app.currencySymbol }}
            - name: FRONTEND_ADDRESS
              value: {{ .Values.app.frontendUrl }}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            {{ if or (.Values.app.resources.limits.cpu) (.Values.app.resources.limits.memory) }}
            limits:
              {{ if .Values.app.resources.limits.cpu }}
              cpu: {{ .Values.app.resources.limits.cpu }}
              {{ end }}
              {{ if .Values.app.resources.limits.memory }}
              memory: {{ .Values.app.resources.limits.memory }}
              {{ end }}
            {{ end }}
            requests:
              cpu: {{ .Values.app.resources.requests.cpu }}
              memory: {{ .Values.app.resources.requests.memory }}
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: {{ .Values.app.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.app.startupProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
      restartPolicy: Always
