{{ if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  strategy:
    type: {{ .Values.frontend.strategyType }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      name: {{ .Release.Name }}-frontend
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: {{ .Release.Name }}-frontend
          image: harbor.sch.bme.hu/org-kir-dev/kir-pay-snyt:latest
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            {{ if or (.Values.frontend.resources.limits.cpu) (.Values.frontend.resources.limits.memory) }}
            limits:
              {{ if .Values.frontend.resources.limits.cpu }}
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              {{ end }}
              {{ if .Values.frontend.resources.limits.memory }}
              memory: {{ .Values.frontend.resources.limits.memory }}
              {{ end }}
            {{ end }}
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}

          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: {{ .Values.frontend.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.frontend.startupProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.livenessProbe.failureThreshold }}
      restartPolicy: Always
{{ end }}
