apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: ghcr.io/simonyiszk/kir-pay
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: DATABASE_HOST
              value: {{ .Release.Name }}-postgresql:5432
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.global.postgresql.auth.database }}
            - name: CURRENCY_SYMBOL
              value: {{ .Values.app.currencySymbol }}
            - name: FRONTEND_ADDRESS
              value: {{ .Values.app.frontendUrl }}
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
