{{ if .Values.app.useIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.app.maxBodySize }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: le-http01
    kubernetes.io/tls-acme: 'true'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.app.host }}
      secretName: {{ .Chart.Name }}-cert
  rules:
    - host: {{ .Values.app.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: 80
{{ end }}
