{{ if and .Values.postgresql.enabled .Values.postgresBackup.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-postgres-backup-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  GOOGLE_SERVICE_ACCOUNT_KEY: {{ required "postgresBackup.googleServiceAccount is required when backup is enabled" .Values.postgresBackup.googleServiceAccount | b64enc }}
  DRIVE_PARENT_ID: {{ required "postgresBackup.driveParentId is required when backup is enabled" .Values.postgresBackup.driveParentId | b64enc }}
  DRIVE_ID: {{ required "postgresBackup.driveId is required when backup is enabled" .Values.postgresBackup.driveId | b64enc }}
  PGPASSWORD: {{ required "postgresql.global.postgresql.auth.password is required for backup" .Values.postgresql.global.postgresql.auth.password | b64enc }}
  PGUSER: {{ .Values.postgresql.global.postgresql.auth.username | b64enc }}
type: Opaque
{{ end }}
