create table if not exists accounts
(
    id      integer primary key generated by default as identity,
    name    text           not null,
    email   text,
    phone   text,
    card    text unique check ( card != '' ),
    balance numeric(38, 0) not null check ( balance >= 0 ),
    active  boolean        not null,
    version integer        not null default 0
);
create index if not exists accounts_name_index on accounts (name);
create unique index if not exists accounts_email_unique on accounts (email) where email is not null;

create table if not exists events
(
    id           integer primary key generated by default as identity,
    event        text   not null,
    timestamp    bigint not null,
    message      text   not null,
    performed_by text   not null
);
create index if not exists events_timestamp_index on events (timestamp desc);

create table if not exists principals
(
    id                  integer primary key generated by default as identity,
    name                text    not null unique,
    secret              text    not null,
    role                text    not null check ( role in ('ADMIN', 'TERMINAL') ),
    active              boolean not null,
    can_upload          boolean not null,
    can_transfer        boolean not null,
    can_sell_items      boolean not null,
    can_redeem_vouchers boolean not null,
    can_assign_cards    boolean not null,
    created_at          bigint  not null,
    last_used           bigint  not null,
    version             integer not null default 0
);
create index if not exists principals_name_index on principals (name);

create table if not exists items
(
    id                  integer primary key generated by default as identity,
    name                text           not null,
    alias               text,
    cost                numeric(38, 0) not null check ( cost >= 0 ),
    stock               integer        not null check ( stock >= 0 ),
    enabled             boolean        not null,
    show_on_leaderboard boolean        not null default false,
    version             integer        not null default 0
);
create index if not exists items_name_index on items (name);

create table if not exists vouchers
(
    id         integer primary key generated by default as identity,
    account_id integer references accounts (id) on delete set null,
    item_id    integer not null references items (id) on delete cascade,
    count      integer not null check ( count >= 0 ),
    version    integer not null default 0,
    unique (account_id, item_id)
);

create table if not exists orders
(
    id                  integer primary key generated by default as identity,
    account_id          integer not null references accounts (id) on delete cascade,
    timestamp           bigint  not null,
    idempotency_key     text unique,
    request_fingerprint text
);

create table if not exists idempotent_operations
(
    id                  integer primary key generated by default as identity,
    idempotency_key     text   not null unique,
    operation_type      text   not null,
    request_fingerprint text   not null,
    response_json       text   not null,
    created_at          bigint not null
);
create index if not exists idx_idempotent_operations_created_at on idempotent_operations (created_at);

create table if not exists order_lines
(
    id           integer primary key generated by default as identity,
    order_id     integer        references orders (id) on delete set null,
    item_id      integer        references items (id) on delete set null,
    item_count   integer        not null check ( item_count > 0 ),
    message      text,
    used_voucher boolean        not null,
    paid_amount  numeric(38, 0) not null check ( paid_amount >= 0 )
);

create table if not exists transactions
(
    id           integer primary key generated by default as identity,
    sender_id    integer        references accounts (id) on delete set null,
    recipient_id integer        references accounts (id) on delete set null,
    type         text           not null check ( type in ('TOP_UP', 'TRANSFER', 'CHARGE') ),
    amount       numeric(38, 0) not null check ( amount > 0 ),
    message      text,
    timestamp    bigint         not null,
    fingerprint  text           not null unique,
    check ( type != 'TOP_UP' or sender_id is null ),
    check ( type != 'CHARGE' or recipient_id is null ),
    check ( sender_id != recipient_id )
);
create index if not exists transactions_timestamp_index on transactions (timestamp desc);
create index if not exists transactions_type_amount_covering_index on transactions (type) include (amount);
create index if not exists transactions_sender_id_index on transactions (sender_id);
create index if not exists transactions_recipient_id_index on transactions (recipient_id);
create index if not exists orders_account_id_index on orders (account_id);
create index if not exists order_lines_order_id_index on order_lines (order_id);
create index if not exists order_lines_item_id_index on order_lines (item_id);

-- Spring Session JDBC schema (JdbcIndexedSessionRepository), PostgreSQL variant.
-- Owned by Flyway; Spring Session schema initialization is disabled in application.properties.

create table if not exists spring_session
(
    primary_id            char(36) not null,
    session_id            char(36) not null,
    creation_time         bigint   not null,
    last_access_time      bigint   not null,
    max_inactive_interval integer  not null,
    expiry_time           bigint   not null,
    principal_name        varchar(100),
    constraint spring_session_pk primary key (primary_id)
);

create unique index if not exists spring_session_ix1 on spring_session (session_id);
create index if not exists spring_session_ix2 on spring_session (expiry_time);
create index if not exists spring_session_ix3 on spring_session (principal_name);
create index if not exists spring_session_ix4 on spring_session (last_access_time);

create table if not exists spring_session_attributes
(
    session_primary_id char(36)     not null,
    attribute_name     varchar(200) not null,
    attribute_bytes    bytea        not null,
    constraint spring_session_attributes_pk primary key (session_primary_id, attribute_name),
    constraint spring_session_attributes_fk foreign key (session_primary_id) references spring_session (primary_id) on delete cascade
);

-- Application-owned table for queryable device metadata per session.
-- Keyed on spring_session.session_id (the app-visible session id used by the SESSION cookie
-- and the admin API), so metadata is cleaned up on session expiry via CASCADE.

create table if not exists session_metadata
(
    session_id varchar(36) not null primary key,
    ip_address varchar(45),
    user_agent text,
    created_at bigint      not null,
    constraint session_metadata_fk foreign key (session_id) references spring_session (session_id) on delete cascade
);
