spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.driverClassName=org.postgresql.Driver
spring.sql.init.mode=never
spring.autoconfigure.exclude=org.springframework.modulith.events.jdbc.JdbcEventPublicationAutoConfiguration,org.springframework.modulith.events.config.EventPublicationAutoConfiguration
spring.main.allow-bean-definition-overriding=true
