spring.application.name=Kir-Pay
#
spring.output.ansi.enabled=always
spring.threads.virtual.enabled=true
spring.web.error.include-message=always
server.port=${SERVER_PORT:8080}
#
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost:5432}/${POSTGRES_DB:kir-pay}
spring.datasource.username=${POSTGRES_USER:kirpay}
spring.datasource.password=${POSTGRES_PASSWORD:password}
spring.datasource.driverClassName=org.postgresql.Driver
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
#
hu.bme.sch.kirpay.principals[0].name=${ADMINISTRATOR_USERNAME:admin}
hu.bme.sch.kirpay.principals[0].password=${ADMINISTRATOR_PASSWORD:admin}
hu.bme.sch.kirpay.principals[0].role=ADMIN
hu.bme.sch.kirpay.principals[0].can-redeem-vouchers=true
hu.bme.sch.kirpay.principals[0].can-sell-items=true
hu.bme.sch.kirpay.principals[0].can-transfer=true
hu.bme.sch.kirpay.principals[0].can-upload=true
hu.bme.sch.kirpay.principals[0].can-assign-cards=true
hu.bme.sch.kirpay.principals[0].active=true
#
hu.bme.sch.kirpay.app.currency-symbol=${CURRENCY_SYMBOL:JMF}
hu.bme.sch.kirpay.app.show-upload-tab=true
hu.bme.sch.kirpay.app.show-pay-tab=true
hu.bme.sch.kirpay.app.show-balance-tab=true
hu.bme.sch.kirpay.app.show-set-card-tab=true
hu.bme.sch.kirpay.app.show-cart-tab=true
hu.bme.sch.kirpay.app.show-token-tab=true
hu.bme.sch.kirpay.app.show-transfer-tab=true
#
hu.bme.sch.kirpay.backend.frontend-url=${FRONTEND_ADDRESS:http://localhost:3000}
#
#
spring.session.timeout=30m
spring.session.jdbc.initialize-schema=never
#
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,prometheus,metrics
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${METRICS_NAME:kir-pay}
