name: Lint CI

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-linters:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Install Node.js dependencies
      run: npm ci

    - name: ESLint
      run: npm run lint

    - name: Prettier
      run: npx prettier --check .

    - name: TypeScript
      run: npx tsc -b
